Godius.Shop/Models/StatisticsViewModels/PerUserStatisticsViewModel.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;

namespace Godius.Shop.Models.StatisticsViewModels
{
    public class PerUserStatisticsViewModel
    {
		public List<ExpandoObject> RichUsers { get; set; } = new List<ExpandoObject>();
		public List<ExpandoObject> LuckyUsers { get; set; } = new List<ExpandoObject>();
	}
}

Godius.Shop/Controllers/StatisticsControlleController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using Godius.Shop.Data;
using Godius.Shop.Extensions;
using Godius.Shop.Models;
using Godius.Shop.Models.StatisticsViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Godius.Shop.Controllers
{
	public class StatisticsController : Controller
	{
		private readonly ApplicationDbContext _context;
		private readonly UserManager<ApplicationUser> _userManager;

		public StatisticsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
		{
			_context = context;
			_userManager = userManager;
		}

		public async Task<IActionResult> Index()
		{
			return View();
		}

		public async Task<IActionResult> PerItemStatistics()
		{
			var purchases = await _context.PurchaseHistory.Include(P => P.Goods)
														.Include(P => P.ResultItemGoods)
														.ThenInclude(RIG => RIG.ItemGoods)
														.ThenInclude(IG => IG.Item)
														.ToListAsync();

			var result = from purchase in purchases
						 group purchase by purchase.Goods into goodsGroup
						 orderby goodsGroup.Key.SerialCode
						 select goodsGroup;

			return PartialView("_PerItemStatistics", result);
		}

		public async Task<IActionResult> PerUserStatistics()
		{
			// RichUser
			var richUsers = await (from user in _context.Users
								   .Include(U => U.Purchases)
								   .ThenInclude(P => P.Goods)
								   let TotalPurchasePrice = user.Purchases.Sum(P => P.Goods.Price)
								   orderby TotalPurchasePrice descending
								   select new
								   {
									   UserId = user.Id,
									   UserEmail = BoardHelper.GetHidedUserEmail(user.Email),
									   TotalPurchasePrice
								   }.ToExpando())
								   .Take(5).ToListAsync();

			// LuckyUser
			var luckyUsers = await (from user in _context.Users
								    .Include(U => U.Purchases)
								    .ThenInclude(P => P.ResultItemGoods)
								    .ThenInclude(RIG => RIG.ItemGoods)
								    .ThenInclude(IG => IG.Item)
								    let Lucky = user.Purchases.Sum(P => P.ResultItemGoods.ItemGoods.Probability) / user.Purchases.Count
								    where user.Purchases.Count > 0
								    orderby Lucky
									select new
									{
										UserId = user.Id,
										UserEmail = BoardHelper.GetHidedUserEmail(user.Email),
										Lucky,
										TotalPurchaseCount = user.Purchases.Count,
										Items = user.Purchases.Select(P => P.ResultItemGoods.ItemGoods).OrderBy(IG => IG.Probability).Take(5).Select(IG => IG.Item).ToList()
									}.ToExpando())
									.Take(5).ToListAsync();

			return PartialView("_PerUserStatistics", new PerUserStatisticsViewModel { RichUsers = richUsers, LuckyUsers = luckyUsers });
		}
	}
}

Godius.Shop/Views/Statistics/Index.cshtml
@{
	ViewData["Title"] = "통계";
}
<h3>통계</h3>

<ul class="nav nav-tabs" id="tabStatistics">
	<li class="active"><a data-toggle="tab" href="#perItem" id="btnPerItem">아이템</a></li>
	<li><a data-toggle="tab" href="#perUser" id="btnPerUser">유저</a></li>
</ul>

<div class="tab-content">
	<div id="perItem" class="tab-pane fade in active">
	</div>
	<div id="perUser" class="tab-pane fade">
	</div>
</div>

@section scripts {
<script type="text/javascript">
	$(document).ready(function () {
		function renderPerItemStatistics() {
			$.get('@Url.Action("PerItemStatistics", "Statistics")', {}, function (response) {
				$('#perItem').html(response);
			});
		}

		function renderPerUserStatistics() {
			$.get('@Url.Action("PerUserStatistics", "Statistics")', {}, function (response) {
				$('#perUser').html(response);
			});
		}

		renderPerItemStatistics();

		$('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
			var targetId = $(e.target).attr('id') // activated tab
			if (targetId == 'btnPerItem') {
				renderPerItemStatistics();
			} else if (targetId == 'btnPerUser') {
				renderPerUserStatistics();
			}
		});
	});
</script>
}

Godius.Shop/Views/Statistics/_PerItemStatistics.cshtml
@model IEnumerable<IGrouping<Goods, Purchase>>
@{
	ViewData["Title"] = "아이템 통계";
}

<h4>아이템 통계</h4>
<p>
	@foreach (var goodsGroup in Model)
	{
		var goodsItem = goodsGroup.Key;

		<div class="panel panel-default">
			<div class="panel-heading">
				<table>
					<tbody>
						<tr>
							<td rowspan="3" colspan="3" width="60px">
								@if (!String.IsNullOrEmpty(goodsItem.Image))
								{
									<img src="@goodsItem.Image" alt="@goodsItem.Image" title="@goodsItem.Name" class="img-thumbnail" />
								}
							</td>
						</tr>
						<tr>
							<td width="10px"></td>
							<td>
								<b>@goodsItem.Name</b>
							</td>
						</tr>
						<tr>
							<td width="10px"></td>
							<td>
								<small class="text-right">
									(구매 개수 : @goodsItem.PurchaseHistory.Count 개, 매출 : @((goodsItem.PurchaseHistory.Count * goodsItem.Price).ToString("C0")))
								</small>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<div class="panel-body">
				<table class="table table-striped">
					<thead>
						<tr>
							<th>아이템</th>
							<th>획득확률</th>
							<th>실제 획득확률</th>
							<th>획득 개수</th>
						</tr>
					</thead>
					<tbody>
						@foreach (var itemsGoodsItem in goodsItem.ItemsGoods.OrderByDescending(IG => IG.Item.Category).ThenBy(IG => IG.Probability).ThenByDescending(IG => IG.Item.Generation))
						{
							var actualProbability = 0d;
							if (goodsItem.PurchaseHistory.Count > 0)
							{
								actualProbability = ((double)itemsGoodsItem.ResultItemGoods.Count / (double)goodsItem.PurchaseHistory.Count) * 100;
							}

							var textColorClass = "";
							var arrowIcon = "";
							@if (actualProbability > itemsGoodsItem.Probability)
							{
								textColorClass = "text-danger";
								arrowIcon = "<i class='glyphicon glyphicon-arrow-up'></i>";
							}
							else if (actualProbability < itemsGoodsItem.Probability)
							{
								textColorClass = "text-primary";
								arrowIcon = "<i class='glyphicon glyphicon-arrow-down'></i>";
							}
							else
							{
								arrowIcon = "=";
							}


							<tr>
								<td height="50px">
									@if (!String.IsNullOrEmpty(itemsGoodsItem.Item.Image))
									{
										<img src="@itemsGoodsItem.Item.Image" alt="@itemsGoodsItem.Item.Image" title="@itemsGoodsItem.Item.Name" class="img-thumbnail" />
										<br />
									}
								</td>
								<td>
									@itemsGoodsItem.Probability.ToString("F2") %
								</td>
								<td>
									<span class="@textColorClass">
										@actualProbability.ToString("F2") %
										@Html.Raw(arrowIcon)
									</span>
								</td>
								<td>
									@itemsGoodsItem.ResultItemGoods.Count 개
								</td>
							</tr>
						}
					</tbody>
				</table>
			</div>
		</div>
	}
</p>

Godius.Shop/Views/Statistics/_PerUserStatistics.cshtml
@model Godius.Shop.Models.StatisticsViewModels.PerUserStatisticsViewModel
@{
	ViewData["Title"] = "유저 통계";
	//var richUsers = Model.RichUsers as List<IDictionary<string, object>>;
	//var luckyUsers = ViewData["LuckyUsers"] as List<IDictionary<string, object>>;
}

<h4>유저 통계</h4>
<h5><b>최대 구매금액 유저</b></h5>
<table class="table table-striped">
	<thead>
		<tr>
			<th>순위</th>
			<th>아이디</th>
			<th>총 구매금액</th>
		</tr>
	</thead>
	<tbody>
	@for (int i = 1; i <= Model.RichUsers.Count; i++)
	{
		var richUser = Model.RichUsers[i - 1] as dynamic;
		<tr>
			<td>@Html.Raw(i)</td>
			<td>@Html.Raw(richUser.UserEmail)</td>
			<td>@Html.Raw(richUser.TotalPurchasePrice.ToString("C0"))</td>
		</tr>
	}
	</tbody>
</table>
<hr />
<h5><b>최고 행운 유저</b></h5>
<table class="table table-striped">
	<thead>
		<tr>
			<th>순위</th>
			<th>아이디</th>
			<th>누적 당첨 확률</th>
			<th>구매 횟수</th>
		</tr>
	</thead>
	<tbody>
	@for (int i = 1; i <= Model.LuckyUsers.Count; i++)
	{
		var luckyUser = Model.LuckyUsers[i - 1] as dynamic;
		<tr>
			<td>@Html.Raw(i)</td>
			<td>@Html.Raw(luckyUser.UserEmail)</td>
			<td>@Html.Raw(luckyUser.Lucky.ToString("F2")) %</td>
			<td>@Html.Raw(luckyUser.TotalPurchaseCount)</td>
		</tr>
	}
	</tbody>
</table>